const es = {
  title: "Programar envíos",
  intro: "Elige el mensaje, los días y la hora para cada persona.",
  contact: "Usar un contacto guardado",
  manual: "Escribir otro teléfono",
  name: "Nombre",
  phone: "Teléfono",
  channel: "Enviar por",
  message: "Mensaje que se repetirá",
  messageHint: "Este mismo mensaje se enviará en los días elegidos. Hasta 1.000 caracteres.",
  days: "Días de envío",
  everyDay: "Todos los días",
  weekdays: "Lunes a viernes",
  time: "Hora de envío",
  zone: "Zona horaria",
  zoneHint: "La hora corresponde a esta zona, aunque tú o la persona estén en otro país.",
  consent: "Esta persona aceptó recibir estos mensajes por el canal elegido.",
  save: "Guardar programación",
  saved: "Programación guardada en pausa. Actívala cuando esté lista.",
  paused: "En pausa",
  active: "Activo",
  activate: "Activar envío automático",
  pause: "Pausar",
  edit: "Editar",
  delete: "Eliminar",
  deleteConfirm: "¿Eliminar esta programación? No se podrá recuperar.",
  deleted: "Programación eliminada.",
  cancel: "Cancelar edición",
  next: "Próximo envío",
  none: "Aún no tienes mensajes programados.",
  list: "Tus programaciones",
  saveFirst: "Guarda el horario y después activa el envío.",
  login: "Inicia sesión para guardar y administrar tus programaciones.",
  loginButton: "Entrar",
  loading: "Cargando programaciones…",
  notConnected:
    "Falta conectar el servicio de mensajería. Puedes guardar los días y la hora, pero los mensajes todavía no saldrán solos.",
  ready: "Canal conectado. Al activarlo, el envío se procesará aunque cierres la app.",
  accepted: "Aceptado por el servicio; no confirma entrega",
  failed: "El servicio rechazó el envío",
  unknown: "Envío sin confirmar; revisa el servicio antes de repetirlo",
  skipped: "Horario vencido; se omitió este envío",
  sending: "Procesando envío",
  retry: "Volver a intentar",
  new: "Nueva programación",
  scheduleInvalid: "Revisa los datos de la programación.",
  scheduleBadMessage: "Escribe el nombre y un mensaje de hasta 1.000 caracteres.",
  scheduleNeedDays: "Selecciona al menos un día.",
  scheduleBadTime: "Selecciona una hora válida.",
  scheduleBadZone: "Selecciona una zona horaria válida.",
  scheduleBusy:
    "La programación cambió o se está enviando. Actualiza la lista y vuelve a intentarlo.",
  scheduleLimit: "Puedes guardar hasta 20 programaciones.",
  scheduleNotConnected: "Este canal todavía no está conectado para tu cuenta.",
  scheduleConsentRequired: "Confirma que la persona aceptó recibir los mensajes.",
  contactBadPhone: "Revisa el país y escribe el teléfono completo.",
  error: "No se pudo guardar. Inténtalo de nuevo.",
  loadError: "No se pudieron cargar tus programaciones.",
  activated: "Envío automático activado.",
  pausedToast: "Envío automático pausado.",
  back: "Volver al mensaje",
  missingTitle: "Para que los mensajes salgan solos, falta:",
  missingAllowed: "Autorizar tu cuenta para usar el remitente",
  missingAllowedHow: "MESSAGING_ALLOWED_USER_IDS con tu ID de usuario",
  missingCredentials: "Las credenciales del proveedor",
  missingCredentialsHow: "TWILIO_ACCOUNT_SID y TWILIO_AUTH_TOKEN",
  missingScheduler: "Encender el procesador de envíos",
  missingSchedulerHow: "CRON_SECRET y MESSAGING_ENABLED=true",
  missingSenderSms: "Un número de SMS del proveedor",
  missingSenderSmsHow: "TWILIO_SMS_FROM",
  missingSenderWhatsApp: "Un remitente y una plantilla de WhatsApp aprobados",
  missingSenderWhatsAppHow: "TWILIO_WHATSAPP_FROM y TWILIO_WHATSAPP_CONTENT_SID_ES / _EN",
  missingDone: "Listo",
  missingHint: "Se configuran en el hosting, no en la app. Después hay que volver a desplegar.",
  scheduleThis: "Programar este mensaje",
  reason: "Motivo del proveedor",
  reasonCode: "Código del proveedor",
  consentTerms: "Ver los términos del servicio de mensajes",
  smsFooterHint: "Cada SMS lleva al final: «{footer}»",
  providerDelivered: "Entregado al teléfono",
  providerSent: "Enviado a la operadora; entrega sin confirmar todavía",
  providerQueued: "En camino",
  providerUndelivered: "No entregado",
  providerErr30003: "el teléfono está apagado o fuera de cobertura",
  providerErr30004: "el número bloquea mensajes de este tipo",
  providerErr30005: "el número no existe o está dado de baja",
  providerErr30006: "es un teléfono fijo o no recibe SMS",
  providerErr30007: "la operadora lo filtró como spam",
  providerErr30034: "el número remitente aún no está vinculado a la campaña aprobada",
  providerErr21610: "esta persona respondió STOP; no recibirá más mensajes",
};
const en: Record<keyof typeof es, string> = {
  title: "Schedule messages",
  intro: "Choose the message, days and time for each person.",
  contact: "Use a saved contact",
  manual: "Enter another phone number",
  name: "Name",
  phone: "Phone",
  channel: "Send via",
  message: "Message to repeat",
  messageHint: "This same message will be sent on the selected days. Up to 1,000 characters.",
  days: "Sending days",
  everyDay: "Every day",
  weekdays: "Monday to Friday",
  time: "Sending time",
  zone: "Time zone",
  zoneHint: "The time follows this zone, even if you or the recipient are in another country.",
  consent: "This person agreed to receive these messages through the selected channel.",
  save: "Save schedule",
  saved: "Schedule saved and paused. Activate it when ready.",
  paused: "Paused",
  active: "Active",
  activate: "Activate automatic sending",
  pause: "Pause",
  edit: "Edit",
  delete: "Delete",
  deleteConfirm: "Delete this schedule? It cannot be recovered.",
  deleted: "Schedule deleted.",
  cancel: "Cancel editing",
  next: "Next send",
  none: "You have no scheduled messages yet.",
  list: "Your schedules",
  saveFirst: "Save the schedule, then activate sending.",
  login: "Sign in to save and manage your schedules.",
  loginButton: "Sign in",
  loading: "Loading schedules…",
  notConnected:
    "The messaging service still needs to be connected. You can save the days and time, but messages will not send automatically yet.",
  ready: "Channel connected. When enabled, sending will be processed even with the app closed.",
  accepted: "Accepted by the service; delivery not confirmed",
  failed: "The service rejected the message",
  unknown: "Sending unconfirmed; check the service before resending",
  skipped: "Sending time expired; this occurrence was skipped",
  sending: "Processing message",
  retry: "Try again",
  new: "New schedule",
  scheduleInvalid: "Check the schedule details.",
  scheduleBadMessage: "Enter a name and a message of up to 1,000 characters.",
  scheduleNeedDays: "Select at least one day.",
  scheduleBadTime: "Select a valid time.",
  scheduleBadZone: "Select a valid time zone.",
  scheduleBusy: "The schedule changed or is currently sending. Refresh the list and try again.",
  scheduleLimit: "You can save up to 20 schedules.",
  scheduleNotConnected: "This channel is not connected for your account yet.",
  scheduleConsentRequired: "Confirm that the person agreed to receive messages.",
  contactBadPhone: "Check the country and enter the full phone number.",
  error: "Could not save. Try again.",
  loadError: "Could not load your schedules.",
  activated: "Automatic sending activated.",
  pausedToast: "Automatic sending paused.",
  back: "Back to message",
  missingTitle: "For messages to send on their own, this is missing:",
  missingAllowed: "Authorize your account to use the sender",
  missingAllowedHow: "MESSAGING_ALLOWED_USER_IDS with your user ID",
  missingCredentials: "The provider credentials",
  missingCredentialsHow: "TWILIO_ACCOUNT_SID and TWILIO_AUTH_TOKEN",
  missingScheduler: "Turn the delivery processor on",
  missingSchedulerHow: "CRON_SECRET and MESSAGING_ENABLED=true",
  missingSenderSms: "An SMS number from the provider",
  missingSenderSmsHow: "TWILIO_SMS_FROM",
  missingSenderWhatsApp: "An approved WhatsApp sender and template",
  missingSenderWhatsAppHow: "TWILIO_WHATSAPP_FROM and TWILIO_WHATSAPP_CONTENT_SID_ES / _EN",
  missingDone: "Done",
  missingHint: "These are set in the hosting, not in the app. A redeploy is needed afterwards.",
  scheduleThis: "Schedule this message",
  reason: "Reason from the provider",
  reasonCode: "Provider code",
  consentTerms: "See the messaging terms",
  smsFooterHint: "Each SMS ends with: “{footer}”",
  providerDelivered: "Delivered to the phone",
  providerSent: "Handed to the carrier; delivery not confirmed yet",
  providerQueued: "On its way",
  providerUndelivered: "Not delivered",
  providerErr30003: "the phone is off or out of coverage",
  providerErr30004: "the number blocks messages of this kind",
  providerErr30005: "the number does not exist or was disconnected",
  providerErr30006: "it is a landline or cannot receive SMS",
  providerErr30007: "the carrier filtered it as spam",
  providerErr30034: "the sender number is not yet linked to the approved campaign",
  providerErr21610: "this person replied STOP; they will get no more messages",
};
export type ScheduleCopy = typeof es;
export const scheduleCopy = (locale: "es" | "en"): ScheduleCopy => (locale === "es" ? es : en);
