/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiAuthStatusRouteImport } from './routes/api/auth-status'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronMessagesRouteImport } from './routes/api/cron/messages'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthStatusRoute = ApiAuthStatusRouteImport.update({
  id: '/api/auth-status',
  path: '/api/auth-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronMessagesRoute = ApiCronMessagesRouteImport.update({
  id: '/api/cron/messages',
  path: '/api/cron/messages',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/auth-status': typeof ApiAuthStatusRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/messages': typeof ApiCronMessagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/auth-status': typeof ApiAuthStatusRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/messages': typeof ApiCronMessagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/auth-status': typeof ApiAuthStatusRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/messages': typeof ApiCronMessagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/api/auth-status' | '/api/auth/$' | '/api/cron/messages'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/api/auth-status' | '/api/auth/$' | '/api/cron/messages'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/auth-status'
    | '/api/auth/$'
    | '/api/cron/messages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiAuthStatusRoute: typeof ApiAuthStatusRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronMessagesRoute: typeof ApiCronMessagesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth-status': {
      id: '/api/auth-status'
      path: '/api/auth-status'
      fullPath: '/api/auth-status'
      preLoaderRoute: typeof ApiAuthStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/messages': {
      id: '/api/cron/messages'
      path: '/api/cron/messages'
      fullPath: '/api/cron/messages'
      preLoaderRoute: typeof ApiCronMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiAuthStatusRoute: ApiAuthStatusRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronMessagesRoute: ApiCronMessagesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
