/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiAskRouteImport } from './routes/api/ask'
import { Route as ApiAuthStatusRouteImport } from './routes/api/auth-status'
import { Route as ApiComposeRouteImport } from './routes/api/compose'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronMessagesRouteImport } from './routes/api/cron/messages'
import { Route as ApiTwilioStatusRouteImport } from './routes/api/twilio/status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAskRoute = ApiAskRouteImport.update({
  id: '/api/ask',
  path: '/api/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthStatusRoute = ApiAuthStatusRouteImport.update({
  id: '/api/auth-status',
  path: '/api/auth-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiComposeRoute = ApiComposeRouteImport.update({
  id: '/api/compose',
  path: '/api/compose',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronMessagesRoute = ApiCronMessagesRouteImport.update({
  id: '/api/cron/messages',
  path: '/api/cron/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTwilioStatusRoute = ApiTwilioStatusRouteImport.update({
  id: '/api/twilio/status',
  path: '/api/twilio/status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/ask': typeof ApiAskRoute
  '/api/auth-status': typeof ApiAuthStatusRoute
  '/api/compose': typeof ApiComposeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/messages': typeof ApiCronMessagesRoute
  '/api/twilio/status': typeof ApiTwilioStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/ask': typeof ApiAskRoute
  '/api/auth-status': typeof ApiAuthStatusRoute
  '/api/compose': typeof ApiComposeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/messages': typeof ApiCronMessagesRoute
  '/api/twilio/status': typeof ApiTwilioStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/ask': typeof ApiAskRoute
  '/api/auth-status': typeof ApiAuthStatusRoute
  '/api/compose': typeof ApiComposeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/messages': typeof ApiCronMessagesRoute
  '/api/twilio/status': typeof ApiTwilioStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/api/ask'
    | '/api/auth-status'
    | '/api/compose'
    | '/api/auth/$'
    | '/api/cron/messages'
    | '/api/twilio/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/api/ask'
    | '/api/auth-status'
    | '/api/compose'
    | '/api/auth/$'
    | '/api/cron/messages'
    | '/api/twilio/status'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/api/ask'
    | '/api/auth-status'
    | '/api/compose'
    | '/api/auth/$'
    | '/api/cron/messages'
    | '/api/twilio/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiAskRoute: typeof ApiAskRoute
  ApiAuthStatusRoute: typeof ApiAuthStatusRoute
  ApiComposeRoute: typeof ApiComposeRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronMessagesRoute: typeof ApiCronMessagesRoute
  ApiTwilioStatusRoute: typeof ApiTwilioStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ask': {
      id: '/api/ask'
      path: '/api/ask'
      fullPath: '/api/ask'
      preLoaderRoute: typeof ApiAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth-status': {
      id: '/api/auth-status'
      path: '/api/auth-status'
      fullPath: '/api/auth-status'
      preLoaderRoute: typeof ApiAuthStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/compose': {
      id: '/api/compose'
      path: '/api/compose'
      fullPath: '/api/compose'
      preLoaderRoute: typeof ApiComposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/messages': {
      id: '/api/cron/messages'
      path: '/api/cron/messages'
      fullPath: '/api/cron/messages'
      preLoaderRoute: typeof ApiCronMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/twilio/status': {
      id: '/api/twilio/status'
      path: '/api/twilio/status'
      fullPath: '/api/twilio/status'
      preLoaderRoute: typeof ApiTwilioStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiAskRoute: ApiAskRoute,
  ApiAuthStatusRoute: ApiAuthStatusRoute,
  ApiComposeRoute: ApiComposeRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronMessagesRoute: ApiCronMessagesRoute,
  ApiTwilioStatusRoute: ApiTwilioStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
